# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:
  name: 'backend'
  host: 'unagi.api.grai.io'

  replicaCount: 1

  image:
    repository: ghcr.io/grai-io/grai-core/grai-server
    pullPolicy: IfNotPresent
    tag: "0.1.7"

  service:
    port: 8000

frontend:
  name: 'frontend'
  host: 'unagi.app.grai.io'

  replicaCount: 1

  image:
    repository: ghcr.io/grai-io/grai-core/grai-frontend
    pullPolicy: IfNotPresent
    tag: "0.1.1"

  service:
    port: 80

ingress:
  enabled: true
  className: "alb"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: prod-ingress
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:627169567483:certificate/a959b428-8737-4242-82be-10430b7dc469
    alb.ingress.kubernetes.io/ssl-redirect: "443"

superuser:
  username: "null@grai.io"
  password: "super_secret"

postgresql:
  enabled: true

# Setups up postgres helm chart when postgres.enabled=true
global:
  postgresql:
    auth:
      database: 'unagi'
      username: 'unagi'
      password: 'unagi'
      postgresPassword: 'unagi'

connections:
  database:
    host: 'unagi-helm-postgresql'
    port: '5432'
    database: 'unagi'
    username: 'unagi'
    password: 'unagi'