apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  labels:
    app: {{ .Values.backend.name }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      containers:
        - name: {{ .Values.backend.name }}
          imagePullPolicy: "{{ .Values.backend.image.pullPolicy }}"
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 30
          ports:
            - name: {{ .Values.backend.name }}
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          env:
            - name: DB_HOST
              value: {{ .Values.connections.database.host }}
            - name: DB_PORT
              value: "{{ .Values.connections.database.port }}"
            - name: DB_NAME
              value: {{ .Values.connections.database.database }}
            - name: DB_USER
              value: {{ .Values.connections.database.username }}
            - name: DB_PASSWORD
              value: {{ .Values.connections.database.password }}
            - name: SERVER_HOST
              value: {{ .Values.backend.host }}
            - name: FRONTEND_HOST
              value: {{ .Values.frontend.host }}
            - name: CSRF_TRUSTED_ORIGINS
              value: https://{{ .Values.frontend.host }},https://{{ .Values.backend.host }}
            - name: DJANGO_SUPERUSER_USERNAME
              value: {{ .Values.superuser.username }}
            - name: DJANGO_SUPERUSER_PASSWORD
              value: {{ .Values.superuser.password }}
            - name: DJANGO_SUPERUSER_WORKSPACE
              value: {{ .Values.superuser.workspace }}
            - name: FRONTEND_URL
              value: https://{{ .Values.frontend.host }}
            - name: CELERY_BROKER
              value: redis://{{ .Values.connections.redis.host }}:{{ .Values.connections.redis.port }}/0
            - name: CELERY_BACKEND
              value: redis://{{ .Values.connections.redis.host }}:{{ .Values.connections.redis.port }}/0
            - name: SECRET_KEY
              value: 'not-secret'
          {{- with .Values.backend.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.celery_worker.name }}
  labels:
    app: {{ .Values.celery_worker.name }}
spec:
  replicas: {{ .Values.celery_worker.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.celery_worker.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.celery_worker.name }}
    spec:
      containers:
        - name: {{ .Values.celery_worker.name }}
          imagePullPolicy: "{{ .Values.celery_worker.image.pullPolicy }}"
          image: "{{ .Values.celery_worker.image.repository }}:{{ .Values.celery_worker.image.tag | default .Chart.AppVersion }}"
          command: ['/start-celeryworker']
          env:
            - name: DB_HOST
              value: {{ .Values.connections.database.host }}
            - name: DB_PORT
              value: "{{ .Values.connections.database.port }}"
            - name: DB_NAME
              value: {{ .Values.connections.database.database }}
            - name: DB_USER
              value: {{ .Values.connections.database.username }}
            - name: DB_PASSWORD
              value: {{ .Values.connections.database.password }}
            - name: SERVER_HOST
              value: {{ .Values.backend.host }}
            - name: FRONTEND_HOST
              value: {{ .Values.frontend.host }}
            - name: CSRF_TRUSTED_ORIGINS
              value: https://{{ .Values.frontend.host }},https://{{ .Values.backend.host }}
            - name: DJANGO_SUPERUSER_USERNAME
              value: {{ .Values.superuser.username }}
            - name: DJANGO_SUPERUSER_PASSWORD
              value: {{ .Values.superuser.password }}
            - name: DJANGO_SUPERUSER_WORKSPACE
              value: {{ .Values.superuser.workspace }}
            - name: FRONTEND_URL
              value: https://{{ .Values.frontend.host }}
            - name: CELERY_BROKER
              value: redis://{{ .Values.connections.redis.host }}:{{ .Values.connections.redis.port }}/0
            - name: CELERY_BACKEND
              value: redis://{{ .Values.connections.redis.host }}:{{ .Values.connections.redis.port }}/0
            - name: SECRET_KEY
              value: 'not-secret'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.celery_beat_worker.name }}
  labels:
    app: {{ .Values.celery_beat_worker.name }}
spec:
  replicas: {{ .Values.celery_beat_worker.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.celery_beat_worker.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.celery_beat_worker.name }}
    spec:
      containers:
        - name: {{ .Values.celery_beat_worker.name }}
          imagePullPolicy: "{{ .Values.celery_beat_worker.image.pullPolicy }}"
          image: "{{ .Values.celery_beat_worker.image.repository }}:{{ .Values.celery_beat_worker.image.tag | default .Chart.AppVersion }}"
          command: ['/start-celerybeat']
          env:
            - name: DB_HOST
              value: {{ .Values.connections.database.host }}
            - name: DB_PORT
              value: "{{ .Values.connections.database.port }}"
            - name: DB_NAME
              value: {{ .Values.connections.database.database }}
            - name: DB_USER
              value: {{ .Values.connections.database.username }}
            - name: DB_PASSWORD
              value: {{ .Values.connections.database.password }}
            - name: SERVER_HOST
              value: {{ .Values.backend.host }}
            - name: FRONTEND_HOST
              value: {{ .Values.frontend.host }}
            - name: CSRF_TRUSTED_ORIGINS
              value: https://{{ .Values.frontend.host }},https://{{ .Values.backend.host }}
            - name: DJANGO_SUPERUSER_USERNAME
              value: {{ .Values.superuser.username }}
            - name: DJANGO_SUPERUSER_PASSWORD
              value: {{ .Values.superuser.password }}
            - name: DJANGO_SUPERUSER_WORKSPACE
              value: {{ .Values.superuser.workspace }}
            - name: FRONTEND_URL
              value: https://{{ .Values.frontend.host }}
            - name: CELERY_BROKER
              value: redis://{{ .Values.connections.redis.host }}:{{ .Values.connections.redis.port }}/0
            - name: CELERY_BACKEND
              value: redis://{{ .Values.connections.redis.host }}:{{ .Values.connections.redis.port }}/0
            - name: SECRET_KEY
              value: 'not-secret'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app: {{ .Values.frontend.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      containers:
        - name: {{ .Values.frontend.name }}
          imagePullPolicy: "{{ .Values.frontend.image.pullPolicy }}"
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: {{ .Values.frontend.name }}
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          env:
            - name: REACT_APP_SERVER_URL
              value: https://{{ .Values.backend.host }}
