# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:
  name: "backend"
  host: ""

  replicaCount: 1

  image:
    repository: ghcr.io/grai-io/grai-core/grai-server
    pullPolicy: Always
    tag: "0.1.13"

  service:
    port: 8000

  env: {}

frontend:
  name: "frontend"
  host: ""

  image:
    repository: ghcr.io/grai-io/grai-core/grai-frontend
    pullPolicy: Always
    tag: "0.1.2"

  service:
    port: 80

celery_worker:
  name: "celery-worker"

  replicaCount: 1

  image:
    repository: ghcr.io/grai-io/grai-core/grai-server
    pullPolicy: Always
    tag: "0.1.13"

celery_beat_worker:
  name: "celery-beat-worker"

  replicaCount: 1

  image:
    repository: ghcr.io/grai-io/grai-core/grai-server
    pullPolicy: Always
    tag: "0.1.13"

ingress:
  enabled: true
  className: "alb"
  annotations: {}

superuser:
  username: "null@grai.io"
  password: "super_secret"
  workspace: "default"

postgresql:
  enabled: true

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false

# Setups up postgres helm chart when postgres.enabled=true
global:
  postgresql:
    auth:
      database: "grai"
      username: "grai"
      password: "password"
      postgresPassword: "password"

connections:
  database:
    host: "grai-postgresql"
    port: "5432"
    database: "grai"
    username: "grai"
    password: "password"

  redis:
    host: "grai-redis"
    port: "6379"
