# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:
  name: "backend"
  host: ""

  replicaCount: 1

  image:
    repository: ghcr.io/grai-io/grai-core/grai-server
    pullPolicy: IfNotPresent
    tag: "0.1.8"

  service:
    port: 8000

frontend:
  name: "frontend"
  host: ""

  replicaCount: 1

  image:
    repository: ghcr.io/grai-io/grai-core/grai-frontend
    pullPolicy: IfNotPresent
    tag: "0.1.1"

  service:
    port: 80

ingress:
  enabled: true
  className: "alb"
  annotations: {}

superuser:
  username: "null@grai.io"
  password: "super_secret"

postgresql:
  enabled: true

# Setups up postgres helm chart when postgres.enabled=true
global:
  postgresql:
    auth:
      database: "grai"
      username: "grai"
      password: "password"
      postgresPassword: "password"

connections:
  database:
    host: "-postgresql"
    port: "5432"
    database: "grai"
    username: "grai"
    password: "password"
