apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-guide
  labels:
    app: the-guide
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-guide
  template:
    metadata:
      labels:
        app: the-guide
    spec:
      containers:
        - name: the-guide
          image: ghcr.io/grai-io/grai-core/grai-server:0.1.7
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
          ports:
            - name: the-guide
              containerPort: 8000
              protocol: TCP
          env:
            - name: DB_HOST
              value: localhost
            - name: DB_PORT
              value: "5432"
            - name: SECRET_KEY
              value: "hdsfg9087dbfv8ysdf9h8yds9f87h7sd98gf7dsiuhvb"
            - name: SERVER_HOST
              value: unagi.api.grai.io
            - name: FRONTEND_HOST
              value: unagi.app.grai.io
            - name: CSRF_TRUSTED_ORIGINS
              value: https://unagi.api.grai.io,https://unagi.app.grai.io
            - name: DJANGO_SUPERUSER_USERNAME
              value: "null@grai.io"
            - name: DJANGO_SUPERUSER_PASSWORD
              value: "super_secret"
        - name: db-pod
          image: postgres:14.3-alpine
          env:
            - name: POSTGRES_USER
              value: grai
            - name: POSTGRES_PASSWORD
              value: grai
            - name: POSTGRES_DB
              value: grai
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/grai-io/grai-core/grai-frontend:0.1.1
          ports:
            - name: frontend
              containerPort: 80
              protocol: TCP
          env:
            - name: REACT_APP_SERVER_URL
              value: https://unagi.api.grai.io
