apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}-svc
spec:
  ports:
    - name: http
      targetPort: {{ .Values.backend.service.port }}
      port: {{ .Values.backend.service.port }}
  selector:
    app: {{ .Values.backend.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-svc
spec:
  ports:
    - name: http
      targetPort: {{ .Values.frontend.service.port }}
      port: {{ .Values.frontend.service.port }}
  selector:
    app: {{ .Values.frontend.name }}
