apiVersion: v1
kind: Service
metadata:
  name: the-guide-svc
spec:
  ports:
    - name: http
      targetPort: 8000
      port: 8000
  selector:
    app: the-guide
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  ports:
    - name: http
      targetPort: 80
      port: 80
  selector:
    app: frontend
